#!/bin/bash
aseqdump -p "USB MIDI Interface" | \
while IFS=" ," read src ev1 ev2 ch label1 data1 label2 data2 rest; do
    case "$ev1 $ev2 $data1" in
        "Note on 38" ) xdotool click 1 ;;
        "Note on 48" ) xdotool click 1 ;;
        "Note on 64" ) xdotool click 1 ;;
        "Note on 78" ) xdotool click 1 ;;
	"Note on 89" ) xdotool click 1 ;;
    esac
done
